### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by xeno024** [ShankyTiwari/Realtime-Private-Chat-using-Angular-Nodejs-and-Mysql#5]
Hy!

I made the site very difficult to operate. The console is already empty, no problem. But nothing appears on the page. It does not load the registration / login window or anything. What's the problem? On localhost/runs on internal network, loads, but nothing from the outside.
(Sorry for my English)

Please, help me!
Thank you!

**Comment by xeno024** [comment]
I know what the problem is.
I would like to run the project from a subfolder of the server. I rewrote a lot of things, but socket.io somehow doesn't work.
What should I rewrite in this case?

Please, help me!
Thank you!

**Comment by ShankyTiwari** [comment]
Hey, You just had to download the code and extract it now open the extracted folder and run the below steps,
1.` npm install`
2. `node server.js`

And please make sure you have an internet connection since I have imported angular and CSS files from CDN.

Thanks

**Comment by ShankyTiwari** [comment]
Feel free to ask anything!

**Comment by xeno024** [comment]
Hi! It already had. I would like to run the code in a subfolder of the server. There is currently no error on the page, but nothing appears. As if you couldn't invite auth.html / home.html.

config:
**server.js:**      

```
 this.port =  process.env.PORT || 3000;
 this.host = `192.168.0.102`;
```

**index.html:**

> <html ng-app="app">
>     <head>
>         <title>Realtime Private Chat using Angular, Nodejs and Mysql</title>
>         <meta charset="utf-8">
>         <base href="/nodejs/client/">
>         
>         <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" />
>         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
>         <link rel="stylesheet" href="css/style.css"> 
>     </head>
> 
>     
>     <body>
>         <div id="main">
>             
>             <div ng-view></div>
>         </div>
>     </body>
> 
>     
>     <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js"></script>
>     <script src="https://code.angularjs.org/1.6.5/angular-route.min.js"></script>
>     <script src="/nodejs/client/js/ui-bootstrap-2.5.0.min.js"></script>
>     <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.js"></script>
>     
>     <script src="<MYDOMAIN>/nodejs/socket.io/socket.io.js"></script>
>     
>     <script src="/nodejs/client/js/app.service.js"></script>
>     <script src="/nodejs/client/js/app.js"></script>
>     <script src="/nodejs/client/js/auth.controller.js"></script>
>     <script src="/nodejs/client/js/home.controller.js"></script>
> </html>

Please help! What could be the problem?

I have openmediavault (debian) and Nginx.
