### ISSUE TITLE
Regarding Highlighting the particular users in the chatlist with unseen messages

### ISSUE THREAD

**Issue by duttrohan0302** [ShankyTiwari/Realtime-Private-Chat-using-Angular-Nodejs-and-Mysql#6]
Hi Shanky, I am really inspired by your Private Chat app and I have built a very similar app to it. I wanted to know how would one go about when a user logs in all the users who have sent him new messages are highlighted. How do we implement that?

**Comment by ShankyTiwari** [comment]
Hi @duttrohan0302 you can add one more key as `seen` and based on that you highlight the messages.
Watch this [video](https://www.youtube.com/watch?v=vvhC64hQZMk) it's very informative.
